# Generated by Django 5.0.3 on 2024-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Official_Paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='Passport',
            field=models.ImageField(upload_to='Passport_Photo/%y/%m/%d'),
        ),
    ]
