# Generated by Django 5.0.3 on 2024-05-18 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Official_Paper', '0002_alter_papers_passport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='Bith_cirtification',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='id',
        ),
        migrations.AddField(
            model_name='papers',
            name='Birth_cirtification',
            field=models.ImageField(default=None, upload_to='offcial_papers/Birth_cirtification/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papers',
            name='User',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papers',
            name='Driving_Licence',
            field=models.ImageField(upload_to='offcial_papers/Driving_Licence/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='Passport',
            field=models.ImageField(upload_to='offcial_papers/Passport_Photo/%y/%m/%d'),
        ),
    ]
