# Generated by Django 5.0.3 on 2024-05-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Official_Paper', '0003_remove_papers_bith_cirtification_remove_papers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='Driving_Licence',
            field=models.ImageField(upload_to='offcial_papers/Driving_Licence_photo/%y/%m/%d'),
        ),
    ]
