# Generated by Django 5.0.3 on 2024-05-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Official_Paper', '0004_alter_papers_driving_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='Id_Card',
            field=models.ImageField(default=None, upload_to='offcial_papers/Id_Card_Photo/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papers',
            name='Driving_Licence',
            field=models.ImageField(upload_to='offcial_papers/Driving_Licence_Photo/%y/%m/%d'),
        ),
    ]
