# Generated by Django 5.0.3 on 2024-05-18 23:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Official_Paper', '0005_papers_id_card_alter_papers_driving_licence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='papers',
            new_name='paper',
        ),
    ]
