# Generated by Django 5.0.3 on 2024-05-21 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reniew_Requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_driving_license',
            name='Receive_Date',
            field=models.DateField(default='2024-7-18'),
        ),
        migrations.AlterField(
            model_name='personal_driving_license',
            name='Sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personal_id_card',
            name='Full_Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personal_id_card',
            name='Sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
