# Generated by Django 5.0.3 on 2024-05-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reniew_Requests', '0003_personal_driving_license_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_driving_license',
            name='Nationality',
            field=models.CharField(choices=[('Egyptian', 'Egypt')], max_length=255),
        ),
    ]
