# Generated by Django 5.0.3 on 2024-05-07 01:03

import Reniew_Requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reniew_Requests', '0005_alter_personal_driving_license_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_driving_license',
            name='Receive_Date',
            field=models.DateField(verbose_name=Reniew_Requests.models.get_first_day_next_month),
        ),
        migrations.AlterField(
            model_name='personal_id_card',
            name='Receive_Date',
            field=models.DateField(default=Reniew_Requests.models.get_first_day_next_month),
        ),
    ]
