# Generated by Django 5.0.3 on 2024-05-07 01:07

import Reniew_Requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reniew_Requests', '0006_alter_personal_driving_license_receive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_driving_license',
            name='Receive_Date',
            field=models.DateField(default=Reniew_Requests.models.get_first_day_next_month),
        ),
    ]
