# Generated by Django 5.0.3 on 2024-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reniew_Requests', '0007_alter_personal_driving_license_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_driving_license',
            name='Receive_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personal_id_card',
            name='Receive_Date',
            field=models.DateField(),
        ),
    ]
