# Generated by Django 5.0.3 on 2024-03-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.CharField(default=None, max_length=14)),
                ('Name', models.CharField(default=None, max_length=200)),
                ('current_jop', models.CharField(default=None, max_length=200)),
                ('campanies', models.TextField()),
                ('other', models.TextField()),
            ],
        ),
    ]
