# Generated by Django 5.0.3 on 2024-05-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0002_remove_work_career_id_number_remove_work_career_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_career',
            old_name='campanies',
            new_name='Campanies',
        ),
        migrations.RenameField(
            model_name='work_career',
            old_name='current_jop',
            new_name='Current_Jop',
        ),
        migrations.RemoveField(
            model_name='work_career',
            name='other',
        ),
        migrations.AddField(
            model_name='work_career',
            name='Other',
            field=models.TextField(default=None),
        ),
    ]
