# Generated by Django 5.0.3 on 2024-05-21 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tecnical_Report', '0003_alter_report_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Technical_Report',
        ),
    ]
