# Generated by Django 5.0.3 on 2024-05-18 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('National_ID', models.CharField(default=None, max_length=14, primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=200)),
                ('Complaints', models.TextField()),
                ('Sender', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
