# Generated by Django 5.0.3 on 2024-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('National_ID', models.CharField(default=None, max_length=14)),
                ('Name', models.CharField(default=None, max_length=200)),
                ('Complaints', models.TextField()),
            ],
        ),
    ]
