# Generated by Django 5.0.3 on 2024-03-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(default=None, max_length=100)),
                ('certification', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='educational_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(default=None, max_length=14)),
                ('name', models.CharField(default=None, max_length=200)),
                ('Schools', models.CharField(default=None, max_length=200)),
                ('University', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
