# Generated by Django 5.0.3 on 2024-03-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=200)),
                ('Nationality', models.CharField(default=None, max_length=100)),
                ('Marital_state', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=9)),
                ('Blood_quarter', models.CharField(choices=[('A+', 'A'), ('A-', 'A'), ('B', 'B'), ('AB', 'Ab'), ('O', 'O')], default=None, max_length=3)),
                ('Address', models.CharField(default=None, max_length=40)),
                ('BirthDate', models.DateField()),
            ],
        ),
    ]
