# Generated by Django 5.0.3 on 2024-04-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_home_page_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill1', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Skill2', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Skill3', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Skill4', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Skill5', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
            ],
        ),
    ]
