# Generated by Django 5.0.3 on 2024-04-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_technical_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technical_Skill',
        ),
    ]
