# Generated by Django 5.0.3 on 2024-03-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.CharField(default=None, max_length=14)),
                ('Name', models.CharField(default=None, max_length=200)),
                ('husband_or_wife', models.CharField(default=None, max_length=200)),
                ('Sons_number', models.IntegerField()),
                ('sons_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='social_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.CharField(default=None, max_length=14)),
                ('Name', models.CharField(default=None, max_length=200)),
                ('Personel_Card', models.ImageField(upload_to='')),
                ('Marital_state', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=9)),
                ('Phone_Number', models.CharField(default=None, max_length=14)),
                ('Address', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
