# Generated by Django 5.0.3 on 2024-05-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_remove_family_id_remove_social_state_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_state',
            name='Personel_Card',
            field=models.ImageField(upload_to='Social/social_state/Personel_Card/%y/%m/%d'),
        ),
    ]
