# Generated by Django 5.0.3 on 2024-05-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_alter_social_state_personel_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='Sons_number',
        ),
        migrations.RemoveField(
            model_name='family',
            name='husband_or_wife',
        ),
        migrations.RemoveField(
            model_name='family',
            name='sons_name',
        ),
        migrations.RemoveField(
            model_name='social_state',
            name='Name',
        ),
        migrations.AddField(
            model_name='family',
            name='Husband_or_Wife_Name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='Sons_Name1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='Sons_Name2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='Sons_Name3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='Sons_Name4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social_state',
            name='Phone_Number',
            field=models.CharField(default=None, max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='family',
            name='Sons_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
