# Generated by Django 5.0.3 on 2024-05-14 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.CharField(default=None, max_length=100)),
                ('another_diseases', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='health_state',
            fields=[
                ('id_number', models.CharField(default=None, max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200)),
                ('Blood_quarter', models.CharField(choices=[('A+', 'A Plus'), ('A-', 'A Minus'), ('B+', 'B Plus'), ('B-', 'B Minus'), ('AB+', 'Ab Plus'), ('AB-', 'Ab Minus'), ('O+', 'O Plus'), ('O-', 'O Minus')], default=None, max_length=3)),
                ('health_problem', models.CharField(default=None, max_length=500)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
