# Generated by Django 5.0.3 on 2024-03-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='health_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(default=None, max_length=14)),
                ('name', models.CharField(default=None, max_length=200)),
                ('Blood_quarter', models.CharField(choices=[('A+', 'A'), ('A-', 'A'), ('B', 'B'), ('AB', 'Ab'), ('O', 'O')], default=None, max_length=3)),
                ('health_problem', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='medical_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.CharField(default=None, max_length=100)),
                ('another_diseases', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
